Algoritmo "Autonomia de um veículo"

Var

 distance: real
 amountFuel: real
 result: real

Inicio
 escreval("Digite a quantidade de quilômetros percorridos:")
 leia(distance)
 limpatela
 
 escreval("Digite quantos litros de combústivel foram gastos:")
 leia(amountFuel)
 limpatela
 
 result <- distance/amountfuel
 escreval("A autonomia de veículo é de: ", result, " litros/km")

Fimalgoritmo