Algoritmo "Identificador de números positivos ou negativos, ímpar ou par"

Var
numA : inteiro


Inicio

 escreval("Digite um número:")
 leia(numA)
 
 se (( numA ) mod 2 = 0) entao
 escreval ("Seu número é par")
 senao
 escreval("Seu número é ímpar")
 
 fimse
 
 se ( numA > 0) entao
  escreval ("Seu número é positivo")
  senao
  escreval ("Seu número é negativo")
 

 fimse


Fimalgoritmo